activation: torch.nn.LeakyReLU()
average: weighted
base_encoder: paraphrase-mpnet-base-v2
criterion: torch.nn.CrossEntropyLoss(reduction='none')
data_path: /zfsauton/data/public/redman/
dataset: coronary_angio_nlp
device: cuda
end_model_batch_size: 128
end_model_epochs: 20
end_model_lr: 1e-4
end_model_patience: 3
end_model_weight_decay: 1e-4
h_sizes:
- 768
- 256
- 64
- 4
label_model: data_programming
label_model_lr: 0.01
label_model_n_epochs: 100
max_num: 500
min_df: 0.001
model_path: ../models/coronary_angio_cabg/
n_bootstrap: 100
n_classes: 4
n_jobs: 10
ngram_range: !!python/tuple
- 1
- 3
normalize_embeddings: false
preds_path: ../results/coronary_angio_cabg/
q_update_interval: 50
results_path: ../results/coronary_angio_cabg/
self_train_batch_size: 8
self_train_lr: 1e-6
self_train_patience: 8
self_train_thresh: 1-2e-3
self_train_weight_decay: 1e-4
show_progress_bar: true
target_0: medical therapy, no intervention, continue, smoke, management, aspirin, return, ldl, statin, follow-up, follow up
target_1: percutaneous coronary intervention, pci, stent, balloon, milimeter mm, placed, elut, plavix, ticagrelor, brilinta
target_2: coronary artery bypass grafting, cabg, surgeon, disease, significant, severe, emergency, total occlusion, left main mild
target_3: reschedule, incomplete exam, weeks, months, years, days, complicated, reimage, echo, review
topk: 50
use_custom_encoder: false
use_noise_aware_loss: true
